image: node:14.16.0

stages:
  - build
  - deploy

build:SCILLWS1:
  stage: build
  variables:
    GIT_STRATEGY: clone
  before_script:
    - npm install
  script:
    - npm run build:elements
    - rsync -r /home/gitlab-runner/builds/hyQTHNpm/0/scill/gaas/sdks/web-components /var/www/
  cache:
    paths:
      - node_modules/  
  tags:
    - scill-docker-ws-1
  only:
    - master

deploy:SCILLWS1:
  stage: deploy
  variables:
    GIT_STRATEGY: clone
  script:
    - sh /home/gitlab-runner/builds/hyQTHNpm/0/scill/gaas/sdks/web-components/deploy-cdn.sh 
  tags: 
    - scill-ws-1
  only:
    - tags
 

