stages:
  - build
  - deploy

build:SCILLWS1:
  stage: build
  variables:
    GIT_STRATEGY: clone
  before_script:
  script:
    - sh /home/gitlab-runner/builds/_Srna7rb/0/scill/scill-gaas-admin-panel/build.sh
  tags:
    - scill-ws-1
  only:
    - master

deploy:SCILLWS1:
  stage: deploy
  variables:
    GIT_STRATEGY: clone
  script:
    - sh ./docker-cdn.sh 
  tags: 
    - scill-ws-1
  only:
    - tags
 

