stages:
  - build
  - deploy

build:SCILLWS1:
  stage: build
  variables:
    GIT_STRATEGY: clone
  script:
    - cd /home/gitlab-runner/builds/hyQTHNpm/0/scill/gaas/sdks/web-components/ && sh ./build.sh
  tags:
    - scill-ws-1
  only:
    - master
 
